// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async btcDeriveExternalAddress(
    label: string,
    index: number,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('btc_derive_external_address', {
          label,
          index,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async btcUnoccupiedDeriviationIndex(): Promise<Result<number, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('btc_unoccupied_deriviation_index'),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async btcGetExternalAddresess(): Promise<
    Result<DerivedAddressDto[], string>
  > {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('btc_get_external_addresess'),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async btcGetUtxos(): Promise<Result<UtxoDto[], string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('btc_get_utxos') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async btcSyncUtxos(): Promise<Result<UtxoDto[], string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('btc_sync_utxos') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async btcAccountInfo(): Promise<Result<ActiveAccountDto, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('btc_account_info') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async btcBuildTx(req: BtcBuildTx): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('btc_build_tx', { req }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async btcSendTx(req: BtcSendTx): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('btc_send_tx', { req }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
}

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type ActiveAccountDto = {
  /**
   * main external address to accept payments
   */
  address: string
  total_balance: string
}
export type BtcBuildTx = {
  auto_utxo_selection: boolean
  utxos: UtxoOutpoint[] | null
  value: string
  recipient: string
}
export type BtcSendTx = Record<string, never>
export type DerivedAddressDto = { label: string; path: string; address: string }
export type UtxoDto = {
  utxo_id: UtxoOutpoint
  value: string
  deriv_path: string
  address_label: string | null
}
export type UtxoOutpoint = { tx_id: string; vout: string }

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from '@tauri-apps/api/core'
import * as TAURI_API_EVENT from '@tauri-apps/api/event'
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow'

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

export type Result<T, E> =
  | { status: 'ok'; data: T }
  | { status: 'error'; error: E }

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>
      }
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T]

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg)
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            }
          },
        })
      },
    },
  )
}
