// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async getNetworkStatus(): Promise<Result<NetworkStatus, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_network_status') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getWalletBalance(
    address: string,
  ): Promise<Result<WalletBalance, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_wallet_balance', { address }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async estimateTransfer(
    req: TransferRequest,
  ): Promise<Result<TransferEstimation, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('estimate_transfer', { req }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async executeTransfer(): Promise<Result<string, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('execute_transfer') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async verifyAddress(address: string): Promise<Result<boolean, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('verify_address', { address }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async trackToken(address: string): Promise<Result<TrackedTokenInfo, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('track_token', { address }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async untrackToken(tokenAddress: string): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('untrack_token', { tokenAddress }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async anvilSetInitialBalances(
    address: string,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('anvil_set_initial_balances', { address }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
}

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type BlockChain = 'Bitcoin' | 'Ethereum'
export type FeeMode = 'Minimal' | 'Standard' | 'Increased'
export type NetworkStatus = {
  block_number: string
  block_hash: string
  base_fee_per_gas: string | null
}
export type TokenBalance = {
  symbol: string
  balance: string
  decimals: number
  address: string
}
export type TrackedTokenInfo = {
  chain: BlockChain
  symbol: string
  decimals: number
}
export type TransferEstimation = {
  estimated_gas: string
  max_fee_per_gas: string
  fee_ceiling: string
  fee_in_usd: number
}
export type TransferRequest = {
  token_address: string
  amount: string
  recipient: string
  fee_mode: FeeMode
}
export type WalletBalance = { wei: string; tokens: TokenBalance[] }

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from '@tauri-apps/api/core'
import * as TAURI_API_EVENT from '@tauri-apps/api/event'
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow'

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

export type Result<T, E> =
  | { status: 'ok'; data: T }
  | { status: 'error'; error: E }

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>
      }
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T]

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg)
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            }
          },
        })
      },
    },
  )
}
