// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async ethChainInfo(): Promise<Result<ChainInfo, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('eth_chain_info') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async ethGetBalance(address: string): Promise<Result<Balance, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('eth_get_balance', { address }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async ethBuildTransferTx(
    req: PrepareTxReqReq,
  ): Promise<Result<PrepareTxReqRes, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('eth_build_transfer_tx', { req }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async ethSignAndSendTx(): Promise<Result<string, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('eth_sign_and_send_tx') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async ethVerifyAddress(address: string): Promise<Result<boolean, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('eth_verify_address', { address }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async ethTrackToken(address: string): Promise<Result<TokenType, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('eth_track_token', { address }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async ethUntrackToken(tokenAddress: string): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('eth_untrack_token', { tokenAddress }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async ethAnvilSetInitialBalances(
    address: string,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('eth_anvil_set_initial_balances', { address }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
}

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type Balance = { wei: string; tokens: TokenBalance[] }
export type BlockChain = 'Bitcoin' | 'Ethereum'
export type ChainInfo = {
  block_number: string
  block_hash: string
  base_fee_per_gas: string | null
}
export type FeeMode = 'Minimal' | 'Standard' | 'Increased'
export type PrepareTxReqReq = {
  token_address: string
  amount: string
  recipient: string
  fee_mode: FeeMode
}
export type PrepareTxReqRes = {
  estimated_gas: string
  max_fee_per_gas: string
  fee_ceiling: string
  fee_in_usd: number
}
export type TokenBalance = {
  symbol: string
  balance: string
  decimals: number
  address: string
}
export type TokenType = { chain: BlockChain; symbol: string; decimals: number }

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from '@tauri-apps/api/core'
import * as TAURI_API_EVENT from '@tauri-apps/api/event'
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow'

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

export type Result<T, E> =
  | { status: 'ok'; data: T }
  | { status: 'error'; error: E }

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>
      }
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T]

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg)
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            }
          },
        })
      },
    },
  )
}
