
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async generateMnemonic() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_mnemonic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mnemonicWordlist() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mnemonic_wordlist") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWallet(mnemonic: string, passphrase: string, name: string, creationType: CreationFlow) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_wallet", { mnemonic, passphrase, name, creationType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWallets() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_wallets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlockWallet(walletName: string, passphrase: string) : Promise<Result<UnlockDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_wallet", { walletName, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlockWalletWithBiometric(walletName: string) : Promise<Result<UnlockDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_wallet_with_biometric", { walletName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isBiometricUnlockSupported() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_biometric_unlock_supported") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isBiometricUnlockEnabled(walletName: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_biometric_unlock_enabled", { walletName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enableBiometricUnlock() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_biometric_unlock") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disableBiometricUnlock(walletName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_biometric_unlock", { walletName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameWallet(newName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_wallet", { newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forgetWallet(walletName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_wallet", { walletName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<Config, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfigSchema() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config_schema") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setConfig(input: Config) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addAccount(chain: BlockChain, label: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_account", { chain, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchAccount(chain: BlockChain, account: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_account", { chain, account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameAccount(chain: BlockChain, account: number, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_account", { chain, account, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchBlockchain(chain: BlockChain) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_blockchain", { chain }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async priceFeed() : Promise<Result<PriceFeedDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("price_feed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateAddress(chain: BlockChain, address: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_address", { chain, address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTransactions(req: ListTransactionsRequest) : Promise<Result<TxRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_transactions", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/

export const MIN_PASSPHRASE_LEN = 4 as const;

/** user-defined types **/

export type AccountSummary = { index: number; name: string }
export type ActiveAccountView = { index: number; 
/**
 * main external address to accept payments
 */
address: string; total_balance: string; utxo: UtxoView[] }
export type BitcoinConfig = { regtest: boolean; 
/**
 * Custom Electrum server URL. Leave blank to use the default.
 */
electrum_server: string | null }
export type BitcoinUnlock = { accounts: AccountSummary[]; active_account: ActiveAccountView }
export type BlockChain = "Bitcoin" | "Ethereum"
export type Config = { eth: EthereumConfig; btc: BitcoinConfig; tor: TorConfig; security: ConfigSecurity }
/**
 * Security and access settings
 */
export type ConfigSecurity = { 
/**
 * Derive private keys without including the wallet passphrase
 */
omit_passphrase_on_private_key: boolean; 
/**
 * Lock the wallet after this many minutes of inactivity
 */
session_inactivity_timeout_mins: number }
export type CreationFlow = "Import" | "Generation"
export type EthereumAccountSummary = { index: number; name: string }
export type EthereumActiveAccountView = { index: number; address: string }
export type EthereumConfig = { 
/**
 * Ethereum JSON-RPC endpoint URL
 */
rpc_url: string; anvil: boolean }
export type EthereumUnlock = { accounts: EthereumAccountSummary[]; active_account: EthereumActiveAccountView }
export type ListTransactionsRequest = { chain: BlockChain; account_index: number; limit: number | null }
export type OutPointRef = { tx_id: string; vout: number }
export type PriceFeedDto = { btc_usd: number; eth_usd: number }
export type TorConfig = { 
/**
 * Route connections through Tor for enhanced privacy
 */
enabled: boolean; 
/**
 * SOCKS5 proxy address. Tor must be running locally.
 * Bitcoin routes Electrum connections through this proxy;
 * Ethereum routes the configured RPC URL through this proxy.
 */
socks5_proxy: string }
export type TxDirection = "incoming" | "outgoing" | "selftransfer"
export type TxRecord = { tx_hash: string; wallet_name: string; chain: BlockChain; account_index: number; direction: TxDirection; status: TxStatus; from_address: string | null; to_address: string | null; amount: string; fee: number | null; block_height: string | null; 
/**
 * Chain-specific JSON payload. Stored verbatim so the frontend can decode
 * it according to the [`chain`] discriminator.
 */
chain_data: string; created_at: string; confirmed_at: string | null }
export type TxStatus = "pending" | "confirmed" | "failed"
export type UnlockDto = { ethereum: EthereumUnlock; bitcoin: BitcoinUnlock; last_used_chain: BlockChain }
export type UtxoView = { utxo_id: OutPointRef; value: string; deriv_path: string; address_label: string | null; confirmed: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
