
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async generateMnemonic() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_mnemonic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWallet(mnemonic: string, passphrase: string, name: string, creationType: CreationFlow) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_wallet", { mnemonic, passphrase, name, creationType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWallets() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_wallets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlockWallet(walletName: string, passphrase: string) : Promise<Result<UnlockDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_wallet", { walletName, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forgetWallet(walletName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_wallet", { walletName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<UIConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addAccount(chain: BlockChain, label: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_account", { chain, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchAccount(chain: BlockChain, account: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_account", { chain, account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchBlockchain(chain: BlockChain) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_blockchain", { chain }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async priceFeed() : Promise<Result<PriceFeedDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("price_feed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async btcDeriveExternalAddress(label: string, index: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("btc_derive_external_address", { label, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async btcUnoccupiedDeriviationIndex() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("btc_unoccupied_deriviation_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async btcListExternalAddresess() : Promise<Result<DerivedAddressDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("btc_list_external_addresess") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async btcListUtxos() : Promise<Result<UtxoDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("btc_list_utxos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethChainInfo() : Promise<Result<ChainInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_chain_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethGetBalance(address: string) : Promise<Result<Balance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_get_balance", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethPrepareSendTx(req: PrepareTxReqReq) : Promise<Result<PrepareTxReqRes, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_prepare_send_tx", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethSignAndSendTx() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_sign_and_send_tx") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethVerifyAddress(address: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_verify_address", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethTrackToken(address: string) : Promise<Result<TokenType, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_track_token", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethUntrackToken(tokenAddress: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_untrack_token", { tokenAddress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethAnvilSetInitialBalances(address: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_anvil_set_initial_balances", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
syncHeightUpdateEvent: SyncHeightUpdateEvent,
syncNewUtxoEvent: SyncNewUtxoEvent,
syncProgressEvent: SyncProgressEvent,
syncWarningEvent: SyncWarningEvent
}>({
syncHeightUpdateEvent: "sync-height-update-event",
syncNewUtxoEvent: "sync-new-utxo-event",
syncProgressEvent: "sync-progress-event",
syncWarningEvent: "sync-warning-event"
})

/** user-defined constants **/

export const MIN_PASSPHRASE_LEN = 4 as const;

/** user-defined types **/

export type AccountIdDto = { index: number; name: string }
export type ActiveAccountDto = { 
/**
 * main external address to accept payments
 */
address: string; total_balance: string }
export type Balance = { wei: string; tokens: TokenBalance[] }
export type BitcoinUnlockDto = { accounts: AccountIdDto[]; active_account: ActiveAccountDto }
export type BlockChain = "Bitcoin" | "Ethereum"
export type ChainInfo = { block_number: string; block_hash: string; base_fee_per_gas: string | null }
export type CreationFlow = "Import" | "Generation"
export type DerivedAddressDto = { label: string; path: string; address: string }
export type EthereumUnlockDto = { address: string }
export type FeeMode = "Minimal" | "Standard" | "Increased"
export type HeightUpdateStatus = "in progress" | "completed"
export type PrepareTxReqReq = { token_address: string; amount: string; recipient: string; fee_mode: FeeMode }
export type PrepareTxReqRes = { estimated_gas: string; max_fee_per_gas: string; fee_ceiling: string; fee_in_usd: number }
export type PriceFeedDto = { btc_usd: number; eth_usd: number }
export type SyncHeightUpdateEvent = { status: HeightUpdateStatus; height: number }
export type SyncNewUtxoEvent = { value: string; total: string }
export type SyncProgressEvent = { progress: number }
export type SyncWarningEvent = { msg: string }
export type TokenBalance = { symbol: string; balance: string; decimals: number; address: string }
export type TokenType = { chain: BlockChain; symbol: string; decimals: number }
export type UIConfig = { eth_anvil: boolean }
export type UnlockDto = { ethereum: EthereumUnlockDto; bitcoin: BitcoinUnlockDto; last_used_chain: BlockChain }
export type UtxoDto = { utxo_id: UtxoId; value: string; deriv_path: string; address_label: string | null }
export type UtxoId = { tx_id: string; vout: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
