
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async generateMnemonic() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_mnemonic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWallet(mnemonic: string, passphrase: string, name: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_wallet", { mnemonic, passphrase, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chainStatus() : Promise<Result<ChainStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chain_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWallets() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_wallets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlockWallet(walletName: string, passphrase: string) : Promise<Result<UnlockMsg, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_wallet", { walletName, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forgetWallet(walletName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_wallet", { walletName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<UIConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chainSwitchEvent(chain: Chain) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chain_switch_event", { chain }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async btcDeriveAddress(label: string, index: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("btc_derive_address", { label, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async btcUnoccupiedDeriviationIndex() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("btc_unoccupied_deriviation_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async btcListDerivedAddresess() : Promise<Result<DerivedAddress[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("btc_list_derived_addresess") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async btcListUtxos() : Promise<Result<Utxo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("btc_list_utxos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethChainInfo() : Promise<Result<ChainInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_chain_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethGetBalance(address: string) : Promise<Result<Balance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_get_balance", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethPrepareSendTx(req: PrepareTxReqReq) : Promise<Result<PrepareTxReqRes, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_prepare_send_tx", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethSignAndSendTx() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_sign_and_send_tx") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethVerifyAddress(address: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_verify_address", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethTrackToken(address: string) : Promise<Result<TokenType, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_track_token", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethUntrackToken(tokenAddress: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_untrack_token", { tokenAddress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ethAnvilSetInitialBalances(address: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_anvil_set_initial_balances", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
syncHeightUpdateEvent: SyncHeightUpdateEvent,
syncProgressEvent: SyncProgressEvent,
syncWarningEvent: SyncWarningEvent
}>({
syncHeightUpdateEvent: "sync-height-update-event",
syncProgressEvent: "sync-progress-event",
syncWarningEvent: "sync-warning-event"
})

/** user-defined constants **/

export const MIN_PASSPHRASE_LEN = 4 as const;

/** user-defined types **/

export type Balance = { wei: string; eth_price: string; tokens: TokenBalance[] }
export type BitcoinUnlock = { address: string }
export type Chain = "Bitcoin" | "Ethereum"
export type ChainInfo = { block_number: string; block_hash: string; base_fee_per_gas: string | null }
export type ChainStatus = { height: number }
export type DerivedAddress = { label: string; address: string; deriv_path: string }
export type EthereumUnlock = { address: string }
export type FeeMode = "Minimal" | "Standard" | "Increased"
export type HeightUpdateStatus = "in progress" | "completed"
export type PrepareTxReqReq = { token_address: string; amount: string; recipient: string; fee_mode: FeeMode }
export type PrepareTxReqRes = { estimated_gas: string; max_fee_per_gas: string; fee_ceiling: string; fee_in_usd: number }
export type SyncHeightUpdateEvent = { status: HeightUpdateStatus; height: number }
export type SyncProgressEvent = { progress: number }
export type SyncWarningEvent = { msg: string }
export type TokenBalance = { symbol: string; balance: string; decimals: number; address: string }
export type TokenType = { chain: Chain; symbol: string; decimals: number }
export type UIConfig = { eth_anvil: boolean }
export type UnlockMsg = { ethereum: EthereumUnlock; bitcoin: BitcoinUnlock; last_used_chain: Chain }
export type Utxo = { utxo_id: UtxoId; value: string; deriv_path: string }
export type UtxoId = { tx_id: string; vout: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
